[package]
name = "teloxide-macros"
version = "0.3.1"
description = "The teloxide's procedural macros"
authors = ["p0lunin <dmytro.polunin@gmail.com>"]
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.7"
proc-macro2 = "1.0.19"
syn = { version = "1.0.13",  features = ["full"] }

[lib]
proc-macro = true
